/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `maven-publish`
    signing
    id("buildlogic.java-library-conventions")
}

dependencies {

    implementation(project(":smr"))
    implementation(libs.codehead.metrics)
    implementation(libs.slf4j.api)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation(libs.codehead.metrics.test)
    testImplementation(libs.bundles.testing)
    testImplementation(libs.bundles.logback)

}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "smr-metrics"
            from(components["java"])
            pom {
                name = "State Machine Redux"
                description = "Core Feature Flag library"
                url = "https://github.com/wolpert/state_machine_redux"
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
                developers {
                    developer {
                        id = "wolpert"
                        name = "Ned Wolpert"
                        email = "ned.wolpert@gmail.com"
                    }
                }
                scm {
                    connection = "scm:git:git://github.com/wolpert/state_machine_redux.git"
                    developerConnection = "scm:git:ssh://github.com/wolpert/state_machine_redux.git"
                    url = "https://github.com/wolpert/state_machine_redux/"
                }
            }

        }
    }
    repositories {
        maven {
            val releasesRepoUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            val snapshotsRepoUrl = "https://oss.sonatype.org/content/repositories/snapshots"
            url = uri(if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl)
            name = "ossrh"
            credentials(PasswordCredentials::class)
        }
    }
}
signing {
    useGpgCmd()
    sign(publishing.publications["mavenJava"])
}
tasks.javadoc {
    if (JavaVersion.current().isJava9Compatible) {
        (options as StandardJavadocDocletOptions).addBooleanOption("html5", true)
    }
}